### ISSUE TITLE
Citing your work?

### ISSUE THREAD

**Issue by julioasotodv** [G-U-N/Rectified-Diffusion#1]
Hi,

I am working on a couple of papers related to diffusion design space alternatives, and I would like to citate your work. 

Is there an arXiv prepint?

thank you!

**Comment by G-U-N** [comment]
Hi,

Thank you for reaching out! I have uploaded it to arXiv, but it was on hold (I don't know the reason). Fortunately, the status has now changed to 'submitted'. I anticipate it will be available on arXiv in 1-2 days.

**Comment by julioasotodv** [comment]
Ok good! Will check this weekend then.

Thank you!
